export const topics = [
  {
    slug: 'analysis',
    label: 'Analysis',
    shortLabel: 'Analysis',
    href: '/transparencyproject/analysis',
    color: 'brand-primary',
    iconClass: 'analysis',
    description: 'Data-driven analysis of pricing patterns, market variation, and what the numbers reveal about payer-provider dynamics.',
    icon: '<svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M2 14L6.5 9.5L10 12L16 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  },
  {
    slug: 'policy',
    label: 'Policy & Regulation',
    shortLabel: 'Policy',
    href: '/transparencyproject/policy',
    color: 'brand-dark',
    iconClass: 'policy',
    description: "CMS rulemaking, enforcement, No Surprises Act outcomes, and what's next for federal and state transparency mandates.",
    icon: '<svg width="18" height="18" viewBox="0 0 18 18" fill="none"><rect x="3" y="2" width="12" height="14" rx="1.5" stroke="currentColor" stroke-width="1.5"/><path d="M6 6h6M6 9h6M6 12h3" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/></svg>',
  },
  {
    slug: 'playbook',
    label: 'Field Guides',
    shortLabel: 'Guides',
    href: '/transparencyproject/playbook',
    color: 'brand-accent',
    iconClass: 'playbook',
    description: 'How to benchmark rates, read an MRF, prepare for negotiations, and use transparency data in daily operations.',
    icon: '<svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M9 2v14M2 9h14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/><circle cx="9" cy="9" r="6.5" stroke="currentColor" stroke-width="1.5"/></svg>',
  },
  {
    slug: 'equity',
    label: 'Patient Equity',
    shortLabel: 'Equity',
    href: '/transparencyproject/equity',
    color: 'brand-secondary',
    iconClass: 'equity',
    description: "Price variation's human impact. Surprise billing, access gaps, and tools that put pricing power back in patients' hands.",
    icon: '<svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M9 2C5.5 5 3 8.5 3 11a6 6 0 0012 0c0-2.5-2.5-6-6-9z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg>',
  },
  {
    slug: 'employer',
    label: 'Empowering Employers',
    shortLabel: 'Employer',
    href: '/transparencyproject/employer',
    color: 'brand-accent',
    iconClass: 'employer',
    description: 'Empowering employers with the data and tools to make smarter benefits decisions, negotiate better rates, and lower healthcare costs for their workforce.',
    icon: '<svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M3 15v-1a4 4 0 014-4h4a4 4 0 014 4v1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/><circle cx="9" cy="5.5" r="3" stroke="currentColor" stroke-width="1.5"/></svg>',
  },
] as const;

export type TopicSlug = (typeof topics)[number]['slug'];
